CREATE FUNCTION [dbo].[ENCONTRAR_PERIODO] (@DATA DATETIME) RETURNS VARCHAR(30) AS
BEGIN
	DECLARE @ANO VARCHAR(4) = YEAR(@DATA),
			@MES VARCHAR(2) = MONTH(@DATA),
			@RESULTADO VARCHAR(30),
			@SEMESTRE VARCHAR(2)
	IF (@MES >= 1 AND @MES < 7)
		SET @SEMESTRE = '1º';
	ELSE
		SET @SEMESTRE = '2º';
	SET @RESULTADO = @ANO + ' - ' + @SEMESTRE + ' semestre'
	RETURN @RESULTADO;
END;
