BEGIN

	SELECT COLUNAS.*
	FROM (
		SELECT F.NOME, AVL.nome_resum, AVA.NOTA
		FROM sophia.AVALUNO AS AVA WITH(NOLOCK)
		INNER JOIN sophia.AVALS AS AVL WITH(NOLOCK) ON AVA.AVALIACAO = AVL.CODIGO
		INNER JOIN sophia.ACADEMIC AS A WITH(NOLOCK) ON AVA.IDFK_ACADEMIC = A.CODIGO
		INNER JOIN sophia.MATRICULA AS M WITH(NOLOCK) ON M.CODIGO = A.MATRICULA
		INNER JOIN sophia.FISICA AS F WITH(NOLOCK) ON F.CODIGO = M.FISICA
		INNER JOIN sophia.DISCIPLINAS AS D WITH(NOLOCK) ON A.DISCIPLINA = D.CODIGO
		WHERE A.TURMA = 2 
		AND D.NOME = 'Matemática' 
		AND AVL.nome_resum IS NOT NULL
		AND AVL.ETAPA = 13
	) LINHA
	PIVOT (SUM(NOTA) FOR nome_resum IN ([AI1],[AI2],[T],[LC],[PG])) COLUNAS
	
END