--MATERIAIS
--ESMOVIME -> MOVIMENTAÇÕES DE ESTOQUE E ITENS DA NOTA FISCAL
--ESMOIMPO -> IMPOSTOS DOS ITENS DA NOTA FISCAL
--FAIMPOST -> IMPOSTOS GERAIS DA NOTA FISCAL
--ESMATERI -> MATERIAIS
--ESGRUPO -> GRUPO DE MATERIAIS
--ESSUBGRU -> SUBGRUPOS DE MATERIAIS

--FATURAMENTO
--FAPEDIDO -> CAPA DO PEDIDO
--FAITEMPE -> ITENS DO PEDIDO
--FACONTRO -> CONTROLE DO PEDIDO
--FANFISCA -> CAPA DA NOTA FISCAL


--FINANCEIRO
--GFLANCAM -> LANÇAMENTO FINANCEIRO
--GFCONTA -> CONTA FINANCEIRA
--GFPORTAD -> PORTADORES/BANCOS
--CCPCC -> CONTA GERENCIAL/CONTÁBIL

--GERAIS
--GEEMPRES -> CADASTRO GERAL DAS EMPRESAS
--GETOPERA -> CADASTRO DOS TIPOS DE OPERAÇÕES (CFOP)
