CREATE DATABASE PROJETO

USE PROJETO

CREATE TABLE CLIENTES VALUES (
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(50),
	CPF VARCHAR(13),
	DATA_NASCIMENTO VARCHAR(40),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)
)