CREATE  FUNCTION FVALIDA_NUMEROS (@PALAVRA VARCHAR (1000)) RETURNS VARCHAR (1000) AS 
BEGIN
DECLARE
 @RESULTADO VARCHAR (1000), 
 @LETRA VARCHAR(1),
 @QTD_PALAVRA INTEGER,
 @CONT INTEGER

SET @CONT = 0 
SET @QTD_PALAVRA = LEN(@PALAVRA)
SET @RESULTADO = ''
WHILE @CONT < @QTD_PALAVRA 
 BEGIN 
  SET @CONT = @CONT + 1 
  SET @LETRA = SUBSTRING(@PALAVRA,@CONT,1)
  IF @LETRA  IN ('0','1','2','3','4','5','6','7','8','9' ) 
   BEGIN
    SET @RESULTADO =  @RESULTADO +  @LETRA 
   END
 END

 RETURN @RESULTADO 
END