DECLARE @TEXTO VARCHAR(2000)
SET @TEXTO = ''

SELECT @TEXTO = VALOR + '   -   ' + @TEXTO FROM PEDIDOS WHERE MFN = 5 AND CAMPO = 20

SELECT DISTINCT 
	P.MFN, 
	P.CAMPO,  
	@TEXTO
FROM PEDIDOS  AS P
WHERE MFN = 5 AND CAMPO = 20